# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "vmd" "nvme" "uas" "sd_mod" "sdhci_pci" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-ad889244-70f2-4e51-86db-2b744ac9342c";
      fsType = "btrfs";
      options = [ "subvol=@" "compress-force=zstd" ];
    };

  boot.initrd.luks.devices."luks-ad889244-70f2-4e51-86db-2b744ac9342c".device = "/dev/disk/by-uuid/ad889244-70f2-4e51-86db-2b744ac9342c";
  boot.initrd.luks.devices."luks-94279658-6528-49c0-8bfa-4a7aff566b66".device = "/dev/disk/by-uuid/94279658-6528-49c0-8bfa-4a7aff566b66";

  fileSystems."/home" =
    { device = "/dev/mapper/luks-ad889244-70f2-4e51-86db-2b744ac9342c";
      fsType = "btrfs";
      options = [ "subvol=@home" "compress-force=zstd" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/698D-F82C";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

    fileSystems."/home/pepegtz2024/Games" =
    { device = "/dev/mapper/luks-94279658-6528-49c0-8bfa-4a7aff566b66";
      fsType = "btrfs";
      options = [ "compress-force=zstd" "nofail" "nosuid" "nodev" ];
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
